### ISSUE TITLE
During redemption, program exits

### ISSUE THREAD

**Issue by warsix4** [FailSpy/humble-steam-key-redeemer#10]
```
Traceback (most recent call last):
  File "C:\Users\Cody\Desktop\humble-steam-key-redeemer-main\humblesteamkeysredeemer.py", line 574, in <module>
    redeem_steam_keys(humble_session, revealed_keys)
  File "C:\Users\Cody\Desktop\humble-steam-key-redeemer-main\humblesteamkeysredeemer.py", line 396, in redeem_steam_keys
    write_key(9,key["human_name"])
  File "C:\Users\Cody\Desktop\humble-steam-key-redeemer-main\humblesteamkeysredeemer.py", line 274, in write_key
    key["human_name"] = key["human_name"].replace(",", ".")
TypeError: string indices must be integers
```

I'm back again! The program successfully added a few games to my Steam account but then produced this error and stopped running.

**Comment by FailSpy** [comment]
Thanks for helping me iron this out!

This should sort it:
https://github.com/FailSpy/humble-steam-key-redeemer/commit/c4b0396847e5b85f61da9a07ad311b7c3a847d01

**Comment by warsix4** [comment]
It got further, but another error:

```
Traceback (most recent call last):
  File "C:\Users\Cody\Desktop\humble-steam-key-redeemer-main\humblesteamkeysredeemer.py", line 574, in <module>
    f.write(','.join(row)+"\n")
  File "C:\Users\Cody\Desktop\humble-steam-key-redeemer-main\humblesteamkeysredeemer.py", line 396, in redeem_steam_keys
    owned_content = steam_session.get(STEAM_USERDATA_API).json()
  File "C:\Users\Cody\Desktop\humble-steam-key-redeemer-main\humblesteamkeysredeemer.py", line 274, in write_key
    error_code = blob["purchase_result_details"]
TypeError: string indices must be integers
```

**Comment by FailSpy** [comment]
@warsix4 Sorry you're having issues still! If you wouldn't mind, could you try running it with the latest version of the code, and sending me the error you get from there?

**Comment by FailSpy** [comment]
Closing as I believe this has been resolved with the latest changes

If you're still running into issues feel free to open one
