### ISSUE TITLE
Error while redeeming

### ISSUE THREAD

**Issue by upperdarkness** [FailSpy/humble-steam-key-redeemer#14]
Traceback (most recent call last):
  File "D:\humble-steam-key-redeemer-main\humblesteamkeysredeemer.py", line 780, in <module>
    redeem_steam_keys(humble_session, steam_keys if try_already_revealed else unrevealed_keys)
  File "D:\humble-steam-key-redeemer-main\humblesteamkeysredeemer.py", line 480, in redeem_steam_keys
    write_key(9,key)
  File "D:\humble-steam-key-redeemer-main\humblesteamkeysredeemer.py", line 357, in write_key
    output = "{gamekey},{human_name},{redeemed_key_val}\n".format(**key)
KeyError: 'redeemed_key_val'

**Comment by TubaMT** [comment]
Getting similar errors as well:

Traceback (most recent call last):
  File "C:\Games\humble-steam-key-redeemer-main\humblesteamkeysredeemer.py", line 780, in <module>
    redeem_steam_keys(humble_session, steam_keys if try_already_revealed else unrevealed_keys)
  File "C:\Games\humble-steam-key-redeemer-main\humblesteamkeysredeemer.py", line 468, in redeem_steam_keys
    unownedgames = unownedgames + prompt_skipped(skipped_games)
  File "C:\Games\humble-steam-key-redeemer-main\humblesteamkeysredeemer.py", line 366, in prompt_skipped
    file.write(skipped_game + "\n")
  File "C:\Python39\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 13-17: character maps to <undefined>

**Comment by FailSpy** [comment]
I believe these errors are resolved in the latest commits.

**Comment by TubaMT** [comment]
Thanks for the quick edit! Now it seems to be working!

**Comment by upperdarkness** [comment]
Yes that has fixed it, thankyou!!
