### ISSUE TITLE
.humblecookies not found

### ISSUE THREAD

**Issue by metafarion** [FailSpy/humble-steam-key-redeemer#34]
Hey, trying out the latest build here and the program exits silently, but outputs the following in error.log:

> Traceback (most recent call last):
  File "/home/myuser/humble-steam-key-redeemer-main/humblesteamkeysredeemer.py", line 868, in <module>
    humble_login(driver)
  File "/home/myuser/humble-steam-key-redeemer-main/humblesteamkeysredeemer.py", line 236, in humble_login
    if try_recover_cookies(".humblecookies", driver) and verify_logins_session(driver)[0]:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myuser/humble-steam-key-redeemer-main/humblesteamkeysredeemer.py", line 199, in try_recover_cookies
    raise e
  File "/home/myuser/humble-steam-key-redeemer-main/humblesteamkeysredeemer.py", line 189, in try_recover_cookies
    cookies = pickle.load(open(cookie_file,"rb"))
                          ^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '.humblecookies'

Is this file .humblecookies required to run?

**Comment by FailSpy** [comment]
Hm, what OS are you running on? And what browsers do you have installed?

**Comment by FailSpy** [comment]
To answer your question, that file _shouldn't_ be required to run as the script itself should generate it later. There may be a bug here.

**Comment by FailSpy** [comment]
Aha, it's possible you're on an older commit. I was live updating it  for a little bit there. Try pulling the latest version and see if it's working. I think the thing you're hitting up against was fixed in 66a2090

**Comment by metafarion** [comment]
Oh yeah, you're right.  I guess my timing was just bad.
