### ISSUE TITLE
Fatal error when exporting keys

### ISSUE THREAD

**Issue by metafarion** [FailSpy/humble-steam-key-redeemer#36]
This occurs after choosing to export all keys and entering steam credentials to detect ownership:

> Traceback (most recent call last):
  File "/home/myuser/humble-steam-key-redeemer-main/humblesteamkeysredeemer.py", line 338, in redeem_humble_key
    return respjson["key"]
           ~~~~~~~~^^^^^^^
KeyError: 'key'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/myuser/humble-steam-key-redeemer-main/humblesteamkeysredeemer.py", line 880, in <module>
    export_mode(driver,order_details)
  File "/home/myuser/humble-steam-key-redeemer-main/humblesteamkeysredeemer.py", line 709, in export_mode
    tpk["redeemed_key_val"] = redeem_humble_key(humble_session,tpk)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myuser/humble-steam-key-redeemer-main/humblesteamkeysredeemer.py", line 340, in redeem_humble_key
    return resp.text
           ^^^^
NameError: name 'resp' is not defined

**Comment by FailSpy** [comment]
Huh, yeah that was a failure mode from before Selenium, though I have no idea how that fail mode helped preserve anything. Gonna need to see if I can replicate it to fix this.

**Comment by FailSpy** [comment]
I've implemented _a_ fix, I'm not sure it's the right one, but at the very least it should hopefully prevent the entire script from crashing.
