### ISSUE TITLE
KeyError: 'transfer_parameters'

### ISSUE THREAD

**Issue by SomeoneSomewhereIsMe** [FailSpy/humble-steam-key-redeemer#46]
I'll start by aplogizing and this could just be a simple fix that I just dont know. I'm not very fimilar with python. 

When try run the script I get this transfer parameters error once I enter the steam login info.

Traceback (most recent call last):
  File "C:\Users\XXXi\Downloads\humble-steam-key-redeemer-main\humblesteamkeysredeemer.py", line 957, in <module>
    redeem_steam_keys(driver, steam_keys if try_already_revealed else unrevealed_keys)
  File "C:\Users\XXX\Downloads\humble-steam-key-redeemer-main\humblesteamkeysredeemer.py", line 617, in redeem_steam_keys
    session = steam_login()
              ^^^^^^^^^^^^^
  File "C:\Users\XXX\Downloads\humble-steam-key-redeemer-main\humblesteamkeysredeemer.py", line 332, in steam_login
    session = user.cli_login()
              ^^^^^^^^^^^^^^^^
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python312\Lib\site-packages\steam\webauth.py", line 266, in cli_login
    return self.login(password, captcha, email_code, twofactor_code, language)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python312\Lib\site-packages\steam\webauth.py", line 209, in login
    self._finalize_login(resp)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python312\Lib\site-packages\steam\webauth.py", line 153, in _finalize_login
    self.steam_id = SteamID(login_response['transfer_parameters']['steamid'])
                            ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'transfer_parameters'

Any ideas?

**Comment by FailSpy** [comment]
Hey, no worries. That's what this issues thing is here for.

It looks to me like you might  be using the original Steam Python library, which is a bit borked right now due to the repo possibly being abandoned. 

I have a patched version available as of just a couple days ago at https://github.com/FailSpy/steam-py-lib

Make sure you've got the latest version of the humble steam key redeemer repo cloned, and then do
`pip install -r requirements.txt`
That should install my patched version of Steam Python

If that doesn't work, you can try the more manual thing of:
`pip install git+https://github.com/FailSpy/steam-py-lib.git@master`

I'll leave this issue open for now in case you run into any more issues. Feel free to mention any roadblocks you hit and I'll do what I can to unstick you.

**Comment by SomeoneSomewhereIsMe** [comment]
Hoooooly, thanks for the quick response. 

Tried updating both using the req.txt and manually through the repo, still the same thing. 
When I did try doing it manually it said the requirements already satisfied, which makes sense as I ran the req.txt first. 

But it still fails after I enter my logins including 2fa.

**Comment by FailSpy** [comment]
Just to clarify 'it still fails after I enter my logins including 2fa', you're getting the same error?

**Comment by SomeoneSomewhereIsMe** [comment]
Yeah same error. 

Traceback (most recent call last):
  File "C:\Users\XXXX\Downloads\humble-steam-key-redeemer-main\humblesteamkeysredeemer.py", line 957, in <module>
    redeem_steam_keys(driver, steam_keys if try_already_revealed else unrevealed_keys)
  File "C:\Users\XXXX\Downloads\humble-steam-key-redeemer-main\humblesteamkeysredeemer.py", line 617, in redeem_steam_keys
    session = steam_login()
              ^^^^^^^^^^^^^
  File "C:\Users\XXXX\Downloads\humble-steam-key-redeemer-main\humblesteamkeysredeemer.py", line 332, in steam_login
    session = user.cli_login()
              ^^^^^^^^^^^^^^^^
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python312\Lib\site-packages\steam\webauth.py", line 266, in cli_login
    return self.login(password, captcha, email_code, twofactor_code, language)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python312\Lib\site-packages\steam\webauth.py", line 209, in login
    self._finalize_login(resp)
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python312\Lib\site-packages\steam\webauth.py", line 153, in _finalize_login
    self.steam_id = SteamID(login_response['transfer_parameters']['steamid'])
                            ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'transfer_parameters'

**Comment by FailSpy** [comment]
Okay, I've just tried bumping the version number on the patched library. Go ahead and try doing pip install now.

**Comment by SomeoneSomewhereIsMe** [comment]
That worked. Amazing. THANK YOU SO MUCH, 

Can I buy you a pizza or something?

**Comment by FailSpy** [comment]
Ayy, I'm just glad it worked. Appreciate the offer :P
Enjoy, and feel free to let me know if anything else comes up!
