### ISSUE TITLE
Program exits after asking about skipped.txt contents

### ISSUE THREAD

**Issue by warsix4** [FailSpy/humble-steam-key-redeemer#9]
```
Traceback (most recent call last):
  File "C:\Users\Cody\Desktop\humble-steam-key-redeemer-main\humblesteamkeysredeemer.py", line 571, in <module>
    redeem_steam_keys(humble_session, steam_keys if try_already_revealed else unrevealed_keys)
  File "C:\Users\Cody\Desktop\humble-steam-key-redeemer-main\humblesteamkeysredeemer.py", line 409, in redeem_steam_keys
    if not valid_steam_key(key["redeemed_key_val"]):
  File "C:\Users\Cody\Desktop\humble-steam-key-redeemer-main\humblesteamkeysredeemer.py", line 59, in valid_steam_key
    and all([len(part) == 5])
NameError: name 'part' is not defined
```

This happens when I'm asked about the contents of the skipped.txt file. I do not make changes to the file and hit enter, then the program exits.

Windows 10 20H2
Python 3.9.2

**Comment by FailSpy** [comment]
Resolved now, forgot an iterator. Thanks for the GitHub issue!
